classdef (Abstract) Activity < openminds.abstract.OpenMINDSSchema

    properties (Access = private)
        Required = {'input', 'output'}
    end

    properties
        % Enter a description of this activity.
        description (1,1) string

        % Enter the time (e.g., '20:20:39+00:00') or datetime (e.g., '2018-11-13T20:20:39+00:00') of when the activity ended.
        endedAtTime (1,1) string

        % Add all inputs used by this activity.
        input (1,:) {openminds.core.FileBundle, openminds.core.File}

        % Enter a lookup label for this activity that may help you to more easily find it again.
        lookupLabel (1,1) string

        % Add all outputs generated by this activity.
        output (1,:) {openminds.core.FileBundle, openminds.core.File}

        % Add all important parameters grouped in context-specific sets that were used in this activity.
        parameterSet (1,:) openminds.core.ParameterSet

        % Enter the time (e.g., '20:20:39+00:00') or datetime (e.g., '2018-11-13T20:20:39+00:00') of when the activity started.
        startedAtTime (1,1) string

        % Add all study targets of this activity.
        studyTarget (1,:) {core.category.StudyTarget}
    end

    methods
        function obj = Activity()
        end
    end

end