% Create a new demo subject
subject1 = openminds.core.research.Subject(...
    'species', 'musMusculus', ...
    'biologicalSex', 'male', ...
    'lookupLabel', 'demo_subject1');

ts1 = openminds.core.research.TissueSample(...
    'species', 'musMusculus', ...
    'biologicalSex', 'male', ...
    'lookupLabel', 'demo_tissue_sample1');

% Create the first subject state for the demo subject
subjectStateA = openminds.core.research.SubjectState(...
    'ageCategory', 'adult', ...
    'attribute', 'alive', ...
    'lookupLabel', 'demo-subject-stateA');

% Add the subject state to the studied state of the subject
subject1.studiedState = subjectStateA;

% Display the newly created subject
disp(subject1)
